TYPO3:
  Neos:
    typoScript:
      autoInclude:
        'GesagtGetan.CookieDialogue': true

GesagtGetan:
  CookieDialogue:
    findQuery: imprint
    javascript:
      # Set to `Storage` or `Cookie`
      implementation: Storage
      include: true
      inline: true
    css:
      include: true
      inline: true
