Neos:
  Neos:
    fusion:
      autoInclude:
        'GesagtGetan.CookieDialogue': true

GesagtGetan:
  CookieDialogue:
    findQuery: imprint
    javascript:
      # Set to `Storage` or `Cookie`
      implementation: Storage
      include: true
    css:
      include: true
      position: bottom
      container: 'background:rgba(0,0,0,0.7);color:#fff'
      maxWith: '60em'
      link:
        normal: 'color:#fff;text-decoration:underline'
        hover: 'text-decoration:none'
      button:
        normal: 'color:#fff;border:1px solid #fff;background:transparent'
        hover: 'background:#fff;color:#000'
