TYPO3:
  Neos:
    typoScript:
      autoInclude:
        'GesagtGetan.CookieDialogue': true

GesagtGetan:
  CookieDialogue:
    findQuery: imprint
    translationPackage: 'GesagtGetan.CookieDialogue'
    javascript:
      # Set to `Storage` or `Cookie`
      implementation: Storage
      include: true
      callback:
        accept: null
        decline: null
    css:
      include: true
      # Set to `top` or `bottom`
      position: bottom
      # Set to `left` or `center`
      style: center
      container: 'font-size:12px;background:rgba(0,0,0,0.7);color:#fff'
      maxWith: 60em
      link:
        normal: 'color:#fff;text-decoration:underline'
        hover: 'text-decoration:none'
      button:
        normal: 'color:#fff;border:1px solid #fff;background:transparent'
        hover: 'background:#fff;color:#000'
